version: "3.9"

services:
  mcp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      JWT_SECRET: supersecure
    volumes:
      - ./functions:/app/functions
